# Generated by Django 4.2.7 on 2024-04-04 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.ImageField(upload_to='images')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
            ],
            #options={'db_table': 'gallery_image'}
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('order', models.PositiveIntegerField(default=0)),
                ('highlight', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='album_highlight', to='gallery.image')),
                ('images', models.ManyToManyField(blank=True, related_name='image_albums', to='gallery.image')),
            ],
            options={
                'ordering': ['order', '-pk'],
                #'db_table': 'gallery_album'
            },
        ),
    ]
