# Generated by Django 5.0.4 on 2024-04-13 07:05

import django.core.files.storage.filesystem
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='exif_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='data',
            field=models.ImageField(storage=django.core.files.storage.filesystem.FileSystemStorage, upload_to='images'),
        ),
    ]
