# Generated by Django 5.0.4 on 2024-04-15 03:42

import gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_image_exif_json_alter_image_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='date_taken',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
